# Reference:
# - https://docs.docker.com/compose/compose-file
# - https://eclipsesource.com/blogs/2018/01/11/authenticating-reverse-proxy-with-keycloak/

services:
  # Exposed server that's handling incoming web requests
  ohif_viewer:
    build:
      # Project root
      context: ./../../../../
      # Relative to context
      dockerfile: ./platform/app/.recipes/Nginx-Orthanc-Keycloak/dockerfile
    image: webapp:latest
    container_name: webapp
    volumes:
      # Nginx config
      - ./../../../../platform/app/dist:/var/www/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      # Logs
      - ./logs/nginx:/var/logs/nginx
      # Let's Encrypt
      # - letsencrypt_certificates:/etc/letsencrypt
      # - letsencrypt_challenges:/var/www/letsencrypt
    ports:
      - '443:443' # SSL
      - '80:80' # Web
    depends_on:
      - keycloak
      # - orthanc
    restart: on-failure

  # LINK: https://hub.docker.com/r/jodogne/orthanc-plugins/
  # TODO: Update to use Postgres
  # https://github.com/mrts/docker-postgresql-multiple-databases
  # orthanc:
  #   image: jodogne/orthanc-plugins
  #   hostname: orthanc
  #   container_name: orthanc
  #   volumes:
  #     # Config
  #     - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
  #     # Persist data
  #     - ./volumes/orthanc-db/:/var/lib/orthanc/db/
  #   restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command: start-dev
    hostname: keycloak
    container_name: keycloak
    # volumes:
    #   - ./config/ohif-keycloak-realm.json:/opt/keycloak/data/import/ohif-keycloak-realm.json
    environment:
      # Database
      KC_DB_URL_HOST: postgres
      KC_DB: postgres
      KC_DB_URL: 'jdbc:postgresql://postgres:5432/keycloak'
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_ADMIN_URL: http://localhost:18080/
      KC_HOSTNAME_URL: http://localhost:18080/
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_PROXY_HEADERS: xforwarded
      KEYCLOAK_JDBC_PARAMS: connectTimeout=40000
      KC_LOG_LEVEL: INFO
      KC_HOSTNAME_DEBUG: true
    ports:
      - 18080:8080
    depends_on:
      - postgres
    restart: unless-stopped

  # LINK: https://hub.docker.com/_/postgres/
  postgres:
    image: postgres:15
    hostname: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  keycloak:
