version: 2
snapshot:
  widths:
    - 375
    - 1920
  minHeight: 1080
  percyCSS: ''
  enableJavaScript: false
  cliEnableJavaScript: true
  disableShadowDOM: false
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  networkIdleTimeout: 100
  captureMockedServiceWorker: false
  retry: false
  device-pixel-ratio: 1
upload:
  files: '**/*.{png,jpg,jpeg}'
  ignore: ''
  stripExtensions: false
